const contextTypes = {
  PRODUCTS_CONTEXT: "PRODUCTS_CONTEXT",
  PRODUCTS_ACTION_CONTEXT: "PRODUCTS_ACTION_CONTEXT",
  CARTS_CONTEXT: "CARTS_CONTEXT",
  CARTS_ACTION_CONTEXT: "CARTS_ACTION_CONTEXT",
};
export default contextTypes;
